# Generated by Django 5.0.4 on 2025-02-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
