# Generated by Django 5.0.4 on 2025-02-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_taskencoder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskEncoder',
            new_name='Task',
        ),
    ]
