# Generated by Django 5.1.6 on 2025-02-20 08:38
from itertools import product

from django.db import migrations
import random

def add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()
    all_barcodes = random.sample(range(100000000,1000000000),len(all_products))
    for i in range(len(all_barcodes)):
        product = all_products[i]
        product.barcode = all_barcodes[i]
        product.save()


def reverse_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    for product in Product.objects.all():
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=reverse_barcode),
    ]
