# Generated by Django 5.0.4 on 2025-03-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_employee_city_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salaty',
            new_name='salary',
        ),
    ]
