# Generated by Django 5.0.4 on 2025-03-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_salaty_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='repeat_first_name',
            field=models.BooleanField(default=False),
        ),
    ]
