# Generated by Django 5.0.4 on 2025-03-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_employee_repeat_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='repeat_first_name',
        ),
    ]
