# Generated by Django 4.2.19 on 2025-04-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_vegetables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'permissions': [('can_add_fruit', 'Can add fruit'), ('can_delete_fruit', 'Can delete fruit')]},
        ),
    ]
