# Generated by Django 4.2.19 on 2025-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_alter_fruit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='fruit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
