# Generated by Django 4.2.19 on 2025-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0004_remove_fruit_nutrition_fruit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='description',
        ),
        migrations.AddField(
            model_name='fruit',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
