# Generated by Django 4.2.19 on 2025-04-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0005_remove_fruit_description_fruit_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetables',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vegetables',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='vegetables',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetables',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
