# Generated by Django 5.1.6 on 2025-02-20 23:01

from django.db import migrations
from django.db.models import Case, When, Value, CharField

def price_rare(apps, schema_editor):
    item_price = apps.get_model('main_app', 'Items')
    item_price.objects.all().update(
        rarity = Case(
            When(price__lte = 10,then = Value('Rare')),
            When(price__gte = 11, price__lte = 20, then = Value('Very Rare')),
            When(price__gte = 21, price__lte = 30, then = Value('Extremely Rare')),
            When(price__gte = 31, then= Value('Mega Rare')),
            default=Value('Unknown'),
            output_field=CharField()
        )
    )

def reverse_price_rare(apps, schema_editor):
    item_price = apps.get_model('main_app', 'Items')
    default_price = item_price._meta.get_field('rarity').default or ''

    item_price.objects.update(rarity = default_price)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_items'),
    ]

    operations = [migrations.RunPython(price_rare, reverse_code=reverse_price_rare)]

