# Generated by Django 5.1.6 on 2025-02-21 10:34
from datetime import timedelta

from django.db import migrations
from order_status import StatusChoices


def update_delivery_and_warranty(apps, schema_editor):
    OrderModel = apps.get_model("main_app", "Order")

    # TODO: do it better with F object
    for order in OrderModel.objects.all():
        if order.status == StatusChoices.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == StatusChoices.Completed:
            order.warranty = "24 months"
            order.save()
        elif order.status == StatusChoices.Cancelled:
            order.delete()


def reverse_migration(apps, schema_editor):
    pass




class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [migrations.RunPython(update_delivery_and_warranty, reverse_code=reverse_migration)]

