# Generated by Django 5.0.4 on 2025-02-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_department_rename_birthday_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='works_full_time',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
