# Generated by Django 5.0.4 on 2025-02-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-16 14:30:45.123456+00:00'),
            preserve_default=False,
        ),
    ]
